# Text Preprocessing

### Import Libraries

In [2]:
import pandas as pd
import nltk
import re

### NLTK Resources and Tools

In [3]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\Radhika
[nltk_data]     Sabale\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Radhika
[nltk_data]     Sabale\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Radhika
[nltk_data]     Sabale\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

### Load Clean Dataset

In [5]:
df = pd.read_csv("../data/cleaned_news.csv")
df.head()

,title,text,label
0,Many 'lost' voters say they have found their c...,WASHINGTON/NEW YORK (Reuters) - Ted Wade hasn’...,1
1,"Iranian Revolutionary Guards commander, anothe...",BEIRUT (Reuters) - A commander in Iran s elite...,1
2,Cambodian leader gets China's backing as West ...,PHNOM PENH (Reuters) - Cambodian Prime Ministe...,1
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,David Duke is perhaps one of the most notoriou...,0
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,Hillary Clinton shows her true colors here wit...,0

### Combine Title and Text

In [6]:
df["content"] = df["title"] + " " + df["text"]
df = df[["content","label"]]
df.head()

                                             content  label
0  Many 'lost' voters say they have found their c...      1
1  Iranian Revolutionary Guards commander, anothe...      1
2  Cambodian leader gets China's backing as West ...      1
3   Ex-KKK Grand Wizard: Maine Gov. Right To Call...      0
4  FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...      0

### Create Stop word List and Stemmer

In [7]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

### Text Cleaning Function

In [8]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]',' ',text)
    words = word_tokenize(text)
    filtered_words = []
    for word in words:
        if word not in stop_words:  
            filtered_words.append(stemmer.stem(word))
    return " ".join(filtered_words)

### Preprocessing

In [9]:
df["processed_content"] = df["content"].apply(preprocess_text)
df.head()

,content,label,processed_content
0,Many 'lost' voters say they have found their c...,1,mani lost voter say found candid trump washing...
1,"Iranian Revolutionary Guards commander, anothe...",1,iranian revolutionari guard command anoth figh...
2,Cambodian leader gets China's backing as West ...,1,cambodian leader get china back west condemn c...
3,Ex-KKK Grand Wizard: Maine Gov. Right To Call...,0,ex kkk grand wizard main gov right call black ...
4,FINGER-WAGGING GRANNY HILLARY CLINTON Blows Up...,0,finger wag granni hillari clinton blow activis...

In [10]:
df.to_csv("../data/preprocessed_news.csv", index=0)
print("Preprocessed Dataset Saved Successfully")

Preprocessed Dataset Saved Successfully